name: Demo 6
on:
  push:
    branches: [ main ]
    
jobs:
  echo-parameter:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        id: step-1
        run: echo "{my_value}={My Value IS 55}" >> $GITHUB_OUTPUT
      - name: step two
        run: echo "my output value is ${{ steps.step-1.outputs.my_value }}"
        
